In [333]:
import pandas as pd
data = pd.read_csv('billboard.csv')
data

,artiste,track,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,x4th.week,x5th.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,Destiny's Child,Independent Women Part I,Rock,2000-09-23,2000-11-18,78,63.0,49.0,33.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Santana,"Maria, Maria",Rock,2000-02-12,2000-04-08,15,8.0,6.0,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Savage Garden,I Knew I Loved You,Rock,1999-10-23,2000-01-29,71,48.0,43.0,31.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Madonna,Music,Rock,2000-08-12,2000-09-16,41,23.0,18.0,14.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),Rock,2000-08-05,2000-10-14,57,47.0,45.0,29.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,Ghostface Killah,Cherchez LaGhost,R&B,2000-08-05,2000-08-05,98,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,"Smith, Will",Freakin' It,Rap,2000-02-12,2000-02-12,99,99.0,99.0,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,Zombie Nation,Kernkraft 400,Rock,2000-09-02,2000-09-02,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,"Eastsidaz, The",Got Beef,Rap,2000-07-01,2000-07-01,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,Fragma,Toca's Miracle,R&B,2000-10-28,2000-10-28,99,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
data.dtypes

artiste          object
track            object
genre            object
date.entered     object
date.peaked      object
                 ...
x72nd.week      float64
x73rd.week      float64
x74th.week      float64
x75th.week      float64
x76th.week      float64
Length: 81, dtype: object

In [334]:
data['date.entered'] = pd.to_datetime(data['date.entered'])
data['date.peaked'] = pd.to_datetime(data['date.peaked'])
data['entered_to_peak'] = data['date.peaked'] - data['date.entered']
data['entered_to_peak'] = data['entered_to_peak'].dt.days
data

,artiste,track,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,x4th.week,x5th.week,...,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week,entered_to_peak
0,Destiny's Child,Independent Women Part I,Rock,2000-09-23,2000-11-18,78,63.0,49.0,33.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56
1,Santana,"Maria, Maria",Rock,2000-02-12,2000-04-08,15,8.0,6.0,5.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56
2,Savage Garden,I Knew I Loved You,Rock,1999-10-23,2000-01-29,71,48.0,43.0,31.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98
3,Madonna,Music,Rock,2000-08-12,2000-09-16,41,23.0,18.0,14.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),Rock,2000-08-05,2000-10-14,57,47.0,45.0,29.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,Ghostface Killah,Cherchez LaGhost,R&B,2000-08-05,2000-08-05,98,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
313,"Smith, Will",Freakin' It,Rap,2000-02-12,2000-02-12,99,99.0,99.0,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
314,Zombie Nation,Kernkraft 400,Rock,2000-09-02,2000-09-02,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
315,"Eastsidaz, The",Got Beef,Rap,2000-07-01,2000-07-01,99,99.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
316,Fragma,Toca's Miracle,R&B,2000-10-28,2000-10-28,99,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [335]:
df2 = data.set_index(['artiste', 'track','genre','date.entered','date.peaked','entered_to_peak']).rename_axis(['week'], axis=1).stack()

In [336]:
df2 = df2.rename_axis(index={-1: 'class'})
df2

artiste          track                     genre  date.entered  date.peaked  entered_to_peak  week
Destiny's Child  Independent Women Part I  Rock   2000-09-23    2000-11-18   56               x1st.week    78.0
                                                                                              x2nd.week    63.0
                                                                                              x3rd.week    49.0
                                                                                              x4th.week    33.0
                                                                                              x5th.week    23.0
                                                                                                           ...
Zombie Nation    Kernkraft 400             Rock   2000-09-02    2000-09-02   0                x1st.week    99.0
                                                                                              x2nd.week    99.0
Eastsidaz, The   Got Beef                  Rap    2000-07-01    2000-07-01   0                x1st.week    99.0
                                                                                              x2nd.week    99.0
Fragma           Toca's Miracle            R&B    2000-10-28    2000-10-28   0                x1st.week    99.0
Length: 5307, dtype: float64

In [331]:
# df3 = df3.rename(columns={
 #   'artiste': 'artiste',
 #   'track': 'track',
 #   'genre': 'genre',
  #  'date.entered': 'date.entered',
 #   'date.peaked': 'date.peaked',
#'entered_to_peak' : 'entered_to_peak',
#'week' : 'wek',
 #   '' : 'Rank'
#})

In [337]:

df3.head(1)

                                                                                                      0
artiste         track                    genre date.entered date.peaked entered_to_peak week
Destiny's Child Independent Women Part I Rock  2000-09-23   2000-11-18  56              x1st.week  78.0

# Am having a hard time printing individual columns

In [338]:
df3['artiste']

KeyError: 'artiste'

# Am not able to extract the week with the code below

In [339]:
df3['week'] = df3['week'].str.extract('(\d+)').astype(int)

KeyError: 'week'